
[workspace]
members = ["app", "entity", "migration"]
resolver = "3"
default-members = ["app"]


[workspace.dependencies]
sea-orm = { version = "1.1.12", features = [
  "macros",
  "runtime-tokio",
  "sqlx-sqlite",
  "debug-print",
] }
