name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install depedencies
      run: apt install -y clang libavcodec-dev libavformat-dev libavutil-dev pkg-config
    - name: Build
      run: cargo build --verbose
      working-directory: ./backend
    - name: Run tests
      run: cargo test --verbose
      working-directory: ./backend
